// Websites/browserbench.org/Speedometer3.0/resources/newssite/news-next/src/components/navlist/navlist.jsx
import { useDataContext } from "@/context/data-context";
import Dropdown from "../dropdown/dropdown";
import NavListItem from "./navlist-item";

import styles from "news-site-css/dist/navbar.module.css";

export default function NavList({ callback, id }) {
    const { content } = useDataContext();

    const navItems = [];
    const dropdownItems = [];

    Object.keys(content).forEach((key) => {
        if (content[key].priority === 1)
            navItems.push(key);
        else if (content[key].priority === 2)
            dropdownItems.push(key);
    });

    return (
        <ul className={styles["navbar-list"]}>
            {navItems.map((key) =>
                <NavListItem id={`${id}-${key}-link`} key={key} label={content[key].name} url={content[key].url} callback={callback} />
            )}
            {dropdownItems.length > 0
                ? <li className={styles["navbar-item"]}>
                    <Dropdown animatedIconClass={styles["navbar-label-icon"]}>
                        {dropdownItems.map((key) =>
                            <NavListItem id={`${id}-${key}-link`} key={key} label={content[key].name} url={content[key].url} callback={callback} itemClass={styles["navbar-dropdown-item"]} />
                        )}
                    </Dropdown>
                </li>
                : null}
        </ul>
    );
}

// Websites/browserbench.org/Speedometer3.1/resources/newssite/news-nuxt/components/atoms/Navlist.vue
<script lang="js">
import { inject } from "vue";
import { useRoute } from "nuxt/app";
import styles from "news-site-css/dist/navbar.module.css";

export default {
    props: {
        callback: Function,
        id: String,
    },
    setup() {
        const { content } = inject("data");

        const navItems = [];
        const dropdownItems = [];

        Object.keys(content).forEach(key => {
            if (content[key].priority === 1)
                navItems.push(key);
            else if (content[key].priority === 2)
                dropdownItems.push(key);
        });

        const route = useRoute();
        return { route, content, navItems, dropdownItems };
    },
    data() {
        return {
            styles,
        }
    }
}
</script>

<template>
    <ul :class="styles['navbar-list']">
        <li v-for="key in navItems" :key="key" :class="styles['navbar-item']">
            <NavlistItem :id="`${id}-${key}-link`" :label="content[key].name" :url="content[key].url" :callback="callback" />
        </li>
        <li v-if="dropdownItems.length > 0" :class="styles['navbar-item']">
            <Dropdown :animated-icon-class="styles['navbar-label-icon']">
                <li v-for="key in dropdownItems" :key="key" :class="[styles['navbar-item'], styles['navbar-dropdown-item']]">
                    <NavlistItem :id="`${id}-${key}-link`" :label="content[key].name" :url="content[key].url" :callback="callback" />
                </li>
            </Dropdown>
        </li>
    </ul>
</template>
