// Websites/browserbench.org/Speedometer3.0/resources/newssite/news-nuxt/components/molecules/Header.vue
<script lang="js">
import styles from "news-site-css/dist/header.module.css";
export default {
  data () {
    return {
      styles
    }
  }
}
</script>

<template>
    <header :class="styles['page-header']">
        <NuxtLink to="/" :class="styles['page-header-title']">
            <TitleIcon />
        </NuxtLink>
    </header>
</template>

// Websites/browserbench.org/Speedometer3.0/resources/newssite/news-next/src/partials/header/header.jsx
import { Link } from "react-router-dom";
import TitleIcon from "@/assets/title-icon";

import styles from "news-site-css/dist/header.module.css";

export default function Header() {
    return (
        <header className={styles["page-header"]}>
            <Link to="/" className={styles["page-header-title"]}>
                <TitleIcon />
            </Link>
        </header>
    );
}
